FROM debian:jessie

ENV GIT_DESCRIBE_TAG=v0.3.0.dev0
ENV CND_URL=http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh

# System packages
RUN apt-get update && \
  apt-get install -y \
    curl \
    git \
    bzip2 && \
  apt-get clean -y

# Install Tini
RUN curl -L https://github.com/krallin/tini/releases/download/v0.6.0/tini > tini && \
    echo "d5ed732199c36a1189320e6c4859f0169e950692f451c03e7854243b95f4234b *tini" | sha256sum -c - && \
    mv tini /usr/local/bin/tini && \
    chmod +x /usr/local/bin/tini

RUN groupadd -r -m -s /bin/bash nbpresent && \
  mkdir -p /src/nbpresent && \
  chown -R nbpresent:nbpresent /src/nbpresent

# Don't run as root, mostly
USER nbpresent
WORKDIR /home/nbpresent

# Install miniconda to /miniconda
RUN curl -LO ${CND_URL} && \
  bash Miniconda-latest-Linux-x86_64.sh -p /home/nbpresent/miniconda -b && \
  rm Miniconda-latest-Linux-x86_64.sh

# Maybe not neccessary?
ENV PATH=/home/nbpresent/miniconda/bin:${PATH}

CMD ["bash"]
