package:
  name: nbpresent
  version: {{ environ.get('GIT_DESCRIBE_TAG', ' ')[1:] }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - nodejs
    - python
    - notebook
    - jupyter
    - funcsigs
  run:
    - python
    - notebook
    - jupyter
    - funcsigs

test:
  imports:
    - notebook
    - nbpresent

about:
  summary: Next generation slides for Jupyter Notebooks
  home: https://github.com/continuumio/nbpresent
  license_file: LICENSE
  license: BSD License
